name: build

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --with build
      - name: Build binary with PyInstaller
        run: poetry run pyinstaller --clean -y songs-to-youtube.spec
      - name: Zip release files
        run: 7z a songs-to-youtube-${{matrix.os}}.zip ./dist/*
      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: songs-to-youtube-${{matrix.os}}.zip
          tag: ${{github.ref}}
