name: build

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller
      - name: Build binary with PyInstaller
        run: pyinstaller --clean -y songs-to-youtube.spec
      - name: Zip release files
        run: 7z a songs-to-youtube-${{matrix.os}}.zip dist/songs-to-youtube
      - name: Upload release files
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          prerelease: false
          files: songs-to-youtube-${{matrix.os}}.zip